/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SignoutImport } from './routes/signout'
import { Route as SigninImport } from './routes/signin'
import { Route as IndexImport } from './routes/index'
import { Route as dashboardDashboardImport } from './routes/(dashboard)/dashboard'
import { Route as dashboardDashboardIndexImport } from './routes/(dashboard)/dashboard.index'
import { Route as dashboardDashboardUsersImport } from './routes/(dashboard)/dashboard.users'
import { Route as dashboardDashboardTasksImport } from './routes/(dashboard)/dashboard.tasks'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardDashboardRoute = dashboardDashboardImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const dashboardDashboardIndexRoute = dashboardDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardDashboardRoute,
} as any)

const dashboardDashboardUsersRoute = dashboardDashboardUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => dashboardDashboardRoute,
} as any)

const dashboardDashboardTasksRoute = dashboardDashboardTasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => dashboardDashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/dashboard/tasks': {
      id: '/(dashboard)/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof dashboardDashboardTasksImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/dashboard/users': {
      id: '/(dashboard)/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof dashboardDashboardUsersImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexImport
      parentRoute: typeof dashboardDashboardImport
    }
  }
}

// Create and export the route tree

interface dashboardDashboardRouteChildren {
  dashboardDashboardTasksRoute: typeof dashboardDashboardTasksRoute
  dashboardDashboardUsersRoute: typeof dashboardDashboardUsersRoute
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardTasksRoute: dashboardDashboardTasksRoute,
  dashboardDashboardUsersRoute: dashboardDashboardUsersRoute,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof dashboardDashboardRouteWithChildren
  '/dashboard/tasks': typeof dashboardDashboardTasksRoute
  '/dashboard/users': typeof dashboardDashboardUsersRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/dashboard/tasks': typeof dashboardDashboardTasksRoute
  '/dashboard/users': typeof dashboardDashboardUsersRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteWithChildren
  '/(dashboard)/dashboard/tasks': typeof dashboardDashboardTasksRoute
  '/(dashboard)/dashboard/users': typeof dashboardDashboardUsersRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/dashboard'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/dashboard/tasks'
    | '/(dashboard)/dashboard/users'
    | '/(dashboard)/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  SignupRoute: typeof SignupRoute
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  SignupRoute: SignupRoute,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin",
        "/signout",
        "/signup",
        "/(dashboard)/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signout": {
      "filePath": "signout.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/(dashboard)/dashboard": {
      "filePath": "(dashboard)/dashboard.tsx",
      "children": [
        "/(dashboard)/dashboard/tasks",
        "/(dashboard)/dashboard/users",
        "/(dashboard)/dashboard/"
      ]
    },
    "/(dashboard)/dashboard/tasks": {
      "filePath": "(dashboard)/dashboard.tasks.tsx",
      "parent": "/(dashboard)/dashboard"
    },
    "/(dashboard)/dashboard/users": {
      "filePath": "(dashboard)/dashboard.users.tsx",
      "parent": "/(dashboard)/dashboard"
    },
    "/(dashboard)/dashboard/": {
      "filePath": "(dashboard)/dashboard.index.tsx",
      "parent": "/(dashboard)/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
