name: "Pull Request Checks"

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  install:
    runs-on: ubuntu-latest
    concurrency:
      group: PR-Checks-install-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

  lint: 
    runs-on: ubuntu-latest
    concurrency:
      group: PR-Checks-lint-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

  build: 
    runs-on: ubuntu-latest
    concurrency:
      group: PR-Checks--build-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm build

  deploy: 
    runs-on: ubuntu-latest
    concurrency:
      group: PR-Stage-Deploy-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: false
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340752840587:role/GitHub
          aws-region: us-east-1
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Deploy PR Stage
        id: sst
        run: pnpm sst deploy --stage pr-${{ github.event.pull_request.number }}

      # - name: Read webApp from output.json
      #   run: |
      #     if [ -f ".sst/outputs.json" ]; then
      #       webApp=$(jq -r '.webApp' .sst/outputs.json)
      #       echo "webApp=$webApp" >> $GITHUB_ENV
      #     else
      #       echo "sst outputs file not found. Exiting."
      #       exit 1
      #     fi

      - name: Capture Stage URL from output
        run: |
          url=$(echo "${{ steps.sst.outputs.stdout }}" | grep -oP '(?<=webApp: ).*')
          echo "webAppURL=$url" >> $GITHUB_ENV


      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const webApp = process.env.webApp;
            const prNumber = context.issue.number;
            const commentBody = `WebApp URL: \`${webApp}\``;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            console.log(comments);

            const existingComment = comments.find(comment => comment.body.startsWith("WebApp URL:"));

            if (existingComment) {
              // Update the existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody,
              });
            } else {
              // Create a new comment if none exists
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody,
              });
            }
    
